ClusterName=lab3
SlurmctldHost=controller
SlurmUser=root
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SwitchType=switch/none
MpiDefault=pmix
ProctrackType=proctrack/cgroup
TaskPlugin=task/cgroup
ReturnToService=2
SlurmctldPort=6817
SlurmdPort=6818
AuthType=auth/munge
CryptoType=crypto/munge
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core_Memory
GresTypes=gpu
AccountingStorageType=accounting_storage/none
JobCompType=jobcomp/none
SlurmctldLogFile=/var/log/slurmctld.log
SlurmdLogFile=/var/log/slurmd.log

NodeName=cpu01 CPUs=8 Boards=1 SocketsPerBoard=2 CoresPerSocket=4 ThreadsPerCore=1 RealMemory=64000 State=UNKNOWN
NodeName=gpu01 CPUs=8 Boards=1 SocketsPerBoard=2 CoresPerSocket=4 ThreadsPerCore=1 RealMemory=84000 Gres=gpu:tesla_v100-sxm2-32gb:1 State=UNKNOWN

PartitionName=cpu Nodes=cpu01,gpu01 Default=YES MaxTime=INFINITE State=UP
PartitionName=gpu Nodes=gpu01 Default=NO MaxTime=INFINITE State=UP
